### ISSUE TITLE
UnboundLocalError: local variable 'correct' referenced before assignment.

### ISSUE THREAD

**Issue by Sijifredo** [terabyte3/discord-ext-forms#25]
Let me start this by telling you guys that I am a complete noob with Discord bot development, so it might be something that I am doing wrong. I will appreciate it if you can provide me with any guidance. Thank you in advance. 

**Describe the bug**
While testing the example(https://github.com/terabyte3/discord-ext-forms) that you guys have on the main page of this repo, I keep getting the error below:

Ignoring exception in command testform:
Traceback (most recent call last):
  File "C:\Users\rosorio\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\rosorio\Documents\PersonalProject\Discord_Trade_Bot\bot.py", line 65, in testform
    result = await form.start()
  File "C:\Users\rosorio\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\forms\form.py", line 297, in start
    if correct:
UnboundLocalError: local variable 'correct' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rosorio\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\rosorio\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\rosorio\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnboundLocalError: local variable 'correct' referenced before assignment
  

**To Reproduce**
I am using Python -V 3.9.7. Also, I installed these requirements:

discord.py
python-dotenv==0.13.0
discord.ext.forms
furo
Sphinx==3.5.4
numpydoc

`import os
import json
import re
import discord
import random

from os.path import join, dirname
from discord import message
from discord import client
from discord.ext.forms.helpers import channel
from dotenv import load_dotenv
from discord.utils import get
#from discord.ext.forms.form import Validator
from discord.ext.forms import Form
from discord.ext import commands

DISCORD_TOKEN = os.environ.get('DISCORD_TOKEN')

load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')

bot = commands.Bot(command_prefix='!')

@bot.event
async def on_ready():
    """ Runs once the bot has established a connection with Discord """

    print(f'{bot.user.name} has connected to Discord')

    # check if bot has connected to guilds
    if len(bot.guilds) > 0:
        print('connected to the following guilds:')

        for guild in bot.guilds:
            print(f'* {guild.name}#{guild.id}')

@bot.command(name="test")
@commands.has_role("Admin")
async def on_test(ctx):
    
    guild = ctx.guild
    channel = ctx.channel
    author = ctx.author
    command = ctx.message.content
    

    # log event on command line
    print(f'* "{author.name}" issued "{command}" in "{channel}" of "{guild}"')

    # post random GIF from the JSON file
    await channel.send(f'* "{author.name}" issued "{command}" in "{channel}" of "{guild}"')

@bot.command()
async def testform(ctx):

    form = Form(ctx,'Title')
    form.add_question('Question 1','first')
    form.add_question('Question 2','second')
    form.add_question('Question 3','third')
    result = await form.start()
    
    embed=discord.Embed(title="details", description=f"1st: `{result.first}`\n 2nd: `{result.second}`\n 3rd: `{result.third}`")

    await ctx.send(embed=embed)
    

if __name__ == "__main__":
    # launch bot
    bot.run(TOKEN)`

**Expected behavior**
the same mechanic that you guys are displaying on the main page of this repo.  

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 pro
 - Visual Studio Code
 
**Additional context**

**Comment by terabyte3** [comment]
Thanks for opening an issue! Someone had just brought this up not too long ago, and I hadn't released the changes to PyPI. Try updating, it should work.

**Comment by terabyte3** [comment]
Any updates?

**Comment by Sijifredo** [comment]
hey, sorry for the late response. So yeah, it works now, but not as it is described in your example. What I was expecting is eliminate the BOT asking me a new question on a new line, but the bot is asking me the second and third questions on the next lines. 

Description of what I am seeing: 
![image](https://user-images.githubusercontent.com/93850826/141233070-a92953fe-0db4-41e6-ab6f-1650bbc672f4.png)

What I was expecting to see is the same mechanic that you have on the main page where basically when the user answers the first question, the bot seems to remove/use the same emb form to show the second question and so on. making the interaction very clean (instead of what You see in my screenshot. ) 

Here is my code:

`import os
import json
import re
import discord
import random

from os.path import join, dirname
from discord import message
from discord import client
from discord.ext.forms.helpers import channel
from dotenv import load_dotenv
from discord.utils import get
#from discord.ext.forms.form import Validator
from discord.ext.forms import Form
from discord.ext import commands


DISCORD_TOKEN = os.environ.get('DISCORD_TOKEN')

load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')


bot = commands.Bot(command_prefix='!')

@bot.event
async def on_ready():
    """ Runs once the bot has established a connection with Discord """

    print(f'{bot.user.name} has connected to Discord')

    # check if bot has connected to guilds
    if len(bot.guilds) > 0:
        print('connected to the following guilds:')

        for guild in bot.guilds:
            print(f'* {guild.name}#{guild.id}')


@bot.command(name="test")
@commands.has_role("Admin")
async def on_test(ctx):
    
    guild = ctx.guild
    channel = ctx.channel
    author = ctx.author
    command = ctx.message.content
    

    # log event on command line
    print(f'* "{author.name}" issued "{command}" in "{channel}" of "{guild}"')

    # post random GIF from the JSON file
    await channel.send(f'* "{author.name}" issued "{command}" in "{channel}" of "{guild}"')


@bot.command()
async def testform(ctx):

    form = Form(ctx,'Title')
    form.add_question('Question 1','first')
    form.add_question('Question 2','second')
    form.add_question('Question 3','third')
    result = await form.start()
    
    embed=discord.Embed(title="details", description=f"1st: `{result.first}`\n 2nd: `{result.second}`\n 3rd: `{result.third}`")

    await ctx.send(embed=embed)
    

if __name__ == "__main__":
    # launch bot
    bot.run(TOKEN)`


I pretty much copy what you have on the main page. Not sure if I am missing anything else. Thank you very much for your help. 

Additional question: 

I am probably pushing it and this is off topic: but do you know or could you point me in the right direction. I am trying to DM a bot in my server and have it send a message to a specific channel in my server. I would like my admins to do the same but I have not been able to find out if it is possible. Anything I have tried tells me that action is not allowed from a DM.

**Comment by terabyte3** [comment]
when you init your form, set `editanddelete=True`:
```py
form = Form(ctx,'Title', editanddelete)
form.add_question('Question 1','first')
form.add_question('Question 2','second')
form.add_question('Question 3','third')
result = await form.start()

embed=discord.Embed(title="details", description=f"1st: `{result.first}`\n 2nd: `{result.second}`\n 3rd: `{result.third}`")

await ctx.send(embed=embed)
```
```

**Comment by Sijifredo** [comment]
Thank you very much for all your assistance. As I said before, I am new to developing Discord Bots, and this library is awesome. Now, I do have a follow-up question. I just found out that discord.py is not going to be active anymore so what does that mean for this library? could I still use it with something like Pycord? Also, if I continue to use Discord.py would my Bot eventually not work if Discord enforces their new standards? Sorry for asking so many questions, if this is too much trouble, would you mind suggesting a place where I can ask these questions? I am pretty new to the python community.  I have focused more on .NET development and do not know many people that are active in the python community. thank you in advance.

**Comment by terabyte3** [comment]
You should be able to use it with any wrapper, so long as it uses the import `discord`. If one doesn't, you could definitely fork it and just change all the `discord` imports to something else.

I just looked up pycord, and it **should** work, even though I haven't tested it.

Discord.py, assuming you aren't using the 2.0 version, will become obsolete in April 2022 (i think), when they will make it so that you have to explicitly request the ability to read message content.

I have no problem with you asking these questions, and if you want you can join the pycord server [here](https://pycord.dev/discord)
