### ISSUE TITLE
Form or Forms

### ISSUE THREAD

**Issue by prakarsh17** [terabyte3/discord-ext-forms#28]
This is a issue I am facing , it is written `from discord.ext.forms import Form` but actually forms is used even while using pip it is said to install discord.ext.forms ,This is all mess the docs also doesnt seem to work pls help.
Making a menu has s in form
```py
@bot.command()
async def menu(ctx):
    embed1=discord.Embed(description="This is embed1")
    embed2=discord.Embed(description="This is embed2")
    embed3=discord.Embed(description="This is embed3")
    rmenu = forms.ReactionMenu(ctx,[embed1,embed2,embed3])
    await rmenu.start()
 ```
 but not others still a mess pls help

**Comment by terabyte3** [comment]
If you import the module like this:
```py
from discord.ext.forms import Form # what is forms, python only knows what 'Form' is
```
then you cannot access the `forms` module directly. You would have to use
```py
from discord.ext import forms # now forms exists
```
